"""Mutator Strategies"""

from enum import Enum


class MutationType(Enum):
    REPHRASE       = "rephrase"
    OBFUSCATE      = "obfuscate"
    ESCALATE       = "escalate"
    SOFTEN         = "soften"
    REFRAME        = "reframe"
    FRAGMENT       = "fragment"
    WRAP           = "wrap"
    LANGUAGE_SWITCH = "lang_switch"
    CROSSOVER      = "crossover"
    ANTI_DEFENSE   = "anti_defense"
    CHAIN          = "chain"

    CONTEXT_MANIPULATION = "context_manipulation"
    DIRECT_INJECTION     = "direct_injection"
    ENCODING_ATTACKS     = "encoding_attacks"
    EXTRACTION_ATTACKS   = "extraction_attacks"
    FEW_SHOT_PRIMING     = "few_shot_priming"
    INDIRECT_INJECTION   = "indirect_injection"
    LINGUISTIC_CONFUSION = "linguistic_confusion"
    LOGIC_TRAPS          = "logic_traps"
    MULTI_TURN           = "multi_turn"
    OUTPUT_CONSTRAINTS   = "output_constraints"
    PAYLOAD_SPLITTING    = "payload_splitting"
    ROLE_HIJACKING       = "role_hijacking"
    TASK_HIJACKING       = "task_hijacking"
    DELIMITER_ATTACKS    = "delimiter_attacks"
    JAILBREAK_VARIANTS   = "jailbreak_variants"
    CONTEXT_PADDING      = "context_padding"
    COMPLETION_ATTACKS   = "completion_attacks"
    FORMAT_MANIPULATION  = "format_manipulation"
    EMOTIONAL_MANIPULATION = "emotional_manipulation"
    CREATIVE_REFRAMING   = "creative_reframing"
    NEGATIVE_EXTRACTION  = "negative_extraction"
    DEEP_INCEPTION       = "deep_inception"
    CIPHER_ATTACKS       = "cipher_attacks"
    MANY_SHOT            = "many_shot"
    PERSONA_MODULATION   = "persona_modulation"
    NESTED_PROMPTS       = "nested_prompts"
    CONFIDENCE_ELICITATION = "confidence_elicitation"
    SELF_DECEPTION       = "self_deception"